version: '3.3'
services:
  mongo-avatar-test:
    image: mongo:6.0.1
    container_name: mongo-avatar-test
    expose:
      - "27017"
    logging:
      driver: none
  elasticsearch-avatar-test:
    container_name: elasticsearch-avatar-test
    image: elastic/elasticsearch:7.15.0
    expose:
      - "9200"
      - "9300"
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    logging:
      driver: none
  avatar-test:
    container_name: avatar-test
    user: $USER_ID:$GID
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch-avatar-test
    volumes:
      - .:/home/mvn-user/build
      - /home/go/.m2-with-cr/:/home/mvn-user/.m2:rw
      - /home/go/maven-repo:/home/mvn-user/maven-repo
    command: >
      /bin/bash -c " \
        echo $HOME && \
        cd /home/mvn-user/build && \
        env && \
        mvn -q clean test scoverage:report -B -s /home/mvn-user/.m2/settings.xml"
    environment:
      - ES_HOST=elasticsearch-avatar-test
      - MONGO_HOST=mongo-avatar-test
      - sun.net.maxDatagramSockets=1024
      - MAVEN_OPTS=-Dmaven.repo.local=/home/mvn-user/maven-repo
      - JAVA_OPTS="-XX:MaxMetaspaceSize=512m"
      - MAVEN_OPTS=-Dsettings.security=/home/mvn-user/.m2/settings-security.xml
