version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4.2
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
    - CLUSTER_NAME=ubirch-es
  kibana:
    image: kibana:4
    ports:
      - "5601:5601"
    links:
      - elasticsearch
  avatar:
    image: ubirch-avatar-service:latest
    ports:
     - "8080:8080"
    links:
     - elasticsearch
    environment:
     - ES_HOST=elasticsearch
     - ES_PORT_HTTP=9200
     - ES_PORT_TCP=9300
     - CLUSTER_NAME=ubirch-es
     - MQTT_URL
     - ENVID=testing
     - MQTT_PASSWORD
     - MQTT_USER
     - DEBUG=true
