#!/bin/bash -x

ES_HOST=192.168.178.23
ES_PORT_TCP=9300
ES_PORT_HTTP=9200
SQS_UBIRCH_TRANSFORMER_OUTBOX="2016-12-24-test-outbox"
SQS_UBIRCH_TRANSFORMER_INBOX="2016-12-24-test-inbox"

export ES_HOST ES_PORT_HTTP ES_PORT_TCP SQS_UBIRCH_TRANSFORMER_INBOX SQS_UBIRCH_TRANSFORMER_OUTBOX
# docker run --rm -p 9200:9200 -p 9300:9300 elasticsearch
# docker run --rm -e ELASTICSEARCH_URL=http://$ES_HOST:$ES_PORT_HTTP -p 5601:5601 kibana
# start
docker run --rm \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e ES_HOST \
  -e ES_PORT_HTTP \
  -e ES_PORT_TCP \
  -e SQS_UBIRCH_TRANSFORMER_INBOX \
  -e SQS_UBIRCH_TRANSFORMER_OUTBOX \
  -p 8080:8080 \
  ubirch-avatar-service
